/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer.Relatorio;

import controler.DAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import viewer.Tela;



/**
 *
 * @author cristiano
 */
public class TelaRelatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form Contas
     */
    public TelaRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendarioRelatorio = new com.github.lgooddatepicker.components.DatePicker();
        btBuscarRelatorio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtReceita = new javax.swing.JLabel();
        txtDespesa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Tela de Relatórios");
        setPreferredSize(new java.awt.Dimension(924, 640));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(calendarioRelatorio);
        calendarioRelatorio.setBounds(30, 20, 210, 30);

        btBuscarRelatorio.setText("BUSCAR");
        btBuscarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btBuscarRelatorio);
        btBuscarRelatorio.setBounds(250, 20, 90, 30);

        jLabel1.setText("Informe um MÊS e ANO(DIA não fará diferença), para podermos trazer o relatório da respectiva data");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 60, 560, 40);

        txtReceita.setForeground(new java.awt.Color(0, 153, 0));
        txtReceita.setText("RECEITA");
        getContentPane().add(txtReceita);
        txtReceita.setBounds(50, 150, 110, 30);

        txtDespesa.setForeground(new java.awt.Color(204, 0, 0));
        txtDespesa.setText("DESPESA");
        getContentPane().add(txtDespesa);
        txtDespesa.setBounds(430, 150, 140, 50);

        jLabel2.setText("R$ :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 160, 30, 30);

        jLabel3.setText("R$ :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 30, 30);

        getAccessibleContext().setAccessibleName("Tela Relatorio");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeactivated
        // Quando a tela for desativada,, setamos que ela podera ser chamda outra vez
        Tela.mnuRelatorio.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameDeactivated

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void btBuscarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarRelatorioActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM");
        String dat = calendarioRelatorio.getDate() + "";
        try {
            dat = formato.format(formato.parse(dat));
        } catch (ParseException ex) {
            Logger.getLogger(TelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            // aqui vamos pegar a data informada e buscar o relatorio
            txtDespesa.setText(mostraRelatorio("Conta" , dat) + "");
        } catch (ParseException ex) {
            Logger.getLogger(TelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            txtReceita.setText(mostraRelatorio("Pagamento" , dat) + "");
        } catch (ParseException ex) {
            Logger.getLogger(TelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btBuscarRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarRelatorio;
    private com.github.lgooddatepicker.components.DatePicker calendarioRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtDespesa;
    private javax.swing.JLabel txtReceita;
    // End of variables declaration//GEN-END:variables
 
     //Método para fazer a soma das contas e pagamentos de uma determinada data(Mês e Ano) passada pelo usuario
     public double mostraRelatorio(String tipo , String data) throws ParseException{
         String sql = "SELECT SUM(PrecoOUValor) FROM historico " 
                + " WHERE Tipo = '" + tipo + "' AND Data = '" + data + "-01' ";
         
        try{
            DAO dao = new DAO();
            Connection conn = dao.conectar();

            Statement st = conn.createStatement();;
            ResultSet rs = st.executeQuery(sql);
            
            double res = 0;           
            while(rs.next()){
                res = rs.getDouble("SUM(PrecoOUValor)");
            }
            return res;
            
        }catch(SQLException sqle){
            sqle.printStackTrace();
        }
        return 0;     
    }
    
    
}
