/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer.Metas;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import viewer.Tela;
import viewer.Tela;
import controler.DAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Caique
 */
public class TelaMeta extends javax.swing.JInternalFrame {
    ButtonGroup grupoBotoes = new ButtonGroup();
    /**
     * Creates new form Contas
     */
    public TelaMeta() {
        initComponents();
        attMetasNaTelaSalario();
        attMetasNaTelaEmprestimos();
        attMetasNaTelaInvestimentos();
        attMetasNaTelaOutros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbProgressoSalario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btReiniciarEmprestimos = new javax.swing.JButton();
        tbMetaSalario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btSalvarMetas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        barraProgressoSalario = new javax.swing.JProgressBar();
        btReiniciarSalario = new javax.swing.JButton();
        barraProgressoEmprestimos = new javax.swing.JProgressBar();
        tbProgressoEmprestimos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        barraProgressoInvestimentos = new javax.swing.JProgressBar();
        tbProgressoInvestimentos = new javax.swing.JTextField();
        tbMetaInvestimentos = new javax.swing.JTextField();
        btReiniciarInvestimentos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        barraProgressoOutrasReceitas = new javax.swing.JProgressBar();
        tbProgressoOutrasReceitas = new javax.swing.JTextField();
        tbMetaOutrasReceitas = new javax.swing.JTextField();
        btReiniciarOutrasReceitas = new javax.swing.JButton();
        tbMetaEmprestimos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Tela de Metas");
        setPreferredSize(new java.awt.Dimension(924, 640));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        tbProgressoSalario.setEnabled(false);
        tbProgressoSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbProgressoSalarioActionPerformed(evt);
            }
        });
        getContentPane().add(tbProgressoSalario);
        tbProgressoSalario.setBounds(110, 30, 70, 30);

        jLabel1.setText("Minhas Metas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 100, 14);

        btReiniciarEmprestimos.setText("Reiniciar");
        btReiniciarEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReiniciarEmprestimosActionPerformed(evt);
            }
        });
        getContentPane().add(btReiniciarEmprestimos);
        btReiniciarEmprestimos.setBounds(300, 80, 130, 23);

        tbMetaSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbMetaSalarioKeyReleased(evt);
            }
        });
        getContentPane().add(tbMetaSalario);
        tbMetaSalario.setBounds(210, 30, 80, 30);

        jLabel3.setText("Progresso");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 10, 80, 14);

        btSalvarMetas.setText("SALVAR");
        btSalvarMetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarMetasActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvarMetas);
        btSalvarMetas.setBounds(491, 10, 100, 23);

        jLabel2.setText("Salário : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 10, 90, 20);
        getContentPane().add(barraProgressoSalario);
        barraProgressoSalario.setBounds(0, 30, 70, 20);

        btReiniciarSalario.setText("Reiniciar");
        btReiniciarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReiniciarSalarioActionPerformed(evt);
            }
        });
        getContentPane().add(btReiniciarSalario);
        btReiniciarSalario.setBounds(300, 40, 130, 23);
        getContentPane().add(barraProgressoEmprestimos);
        barraProgressoEmprestimos.setBounds(0, 90, 70, 20);

        tbProgressoEmprestimos.setEnabled(false);
        tbProgressoEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbProgressoEmprestimosActionPerformed(evt);
            }
        });
        getContentPane().add(tbProgressoEmprestimos);
        tbProgressoEmprestimos.setBounds(110, 80, 70, 30);

        jLabel4.setText("Empréstimos : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 70, 110, 14);

        jLabel5.setText("Investimentos :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 120, 110, 20);
        getContentPane().add(barraProgressoInvestimentos);
        barraProgressoInvestimentos.setBounds(0, 150, 70, 20);

        tbProgressoInvestimentos.setEnabled(false);
        tbProgressoInvestimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbProgressoInvestimentosActionPerformed(evt);
            }
        });
        getContentPane().add(tbProgressoInvestimentos);
        tbProgressoInvestimentos.setBounds(110, 140, 70, 30);
        getContentPane().add(tbMetaInvestimentos);
        tbMetaInvestimentos.setBounds(210, 140, 80, 30);

        btReiniciarInvestimentos.setText("Reiniciar");
        btReiniciarInvestimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReiniciarInvestimentosActionPerformed(evt);
            }
        });
        getContentPane().add(btReiniciarInvestimentos);
        btReiniciarInvestimentos.setBounds(300, 150, 130, 23);

        jLabel6.setText("Outras Receitas : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 180, 110, 14);
        getContentPane().add(barraProgressoOutrasReceitas);
        barraProgressoOutrasReceitas.setBounds(0, 200, 70, 20);

        tbProgressoOutrasReceitas.setEnabled(false);
        tbProgressoOutrasReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbProgressoOutrasReceitasActionPerformed(evt);
            }
        });
        getContentPane().add(tbProgressoOutrasReceitas);
        tbProgressoOutrasReceitas.setBounds(110, 190, 70, 30);
        getContentPane().add(tbMetaOutrasReceitas);
        tbMetaOutrasReceitas.setBounds(210, 190, 80, 30);

        btReiniciarOutrasReceitas.setText("Reiniciar");
        btReiniciarOutrasReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReiniciarOutrasReceitasActionPerformed(evt);
            }
        });
        getContentPane().add(btReiniciarOutrasReceitas);
        btReiniciarOutrasReceitas.setBounds(300, 190, 130, 23);

        tbMetaEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMetaEmprestimosActionPerformed(evt);
            }
        });
        getContentPane().add(tbMetaEmprestimos);
        tbMetaEmprestimos.setBounds(210, 80, 80, 30);

        jLabel7.setText("R$ :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 90, 34, 14);

        jLabel8.setText("R$ :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 150, 34, 14);

        jLabel9.setText("R$ :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 200, 34, 14);

        jLabel10.setText("R$ :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 40, 34, 14);

        jLabel11.setText("R$ :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(190, 90, 34, 14);

        jLabel12.setText("R$ :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(190, 150, 34, 14);

        jLabel13.setText("R$ :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(190, 200, 34, 14);

        jLabel15.setText("R$ :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(80, 40, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeactivated
        // Quando a tela for desativada,, setamos que ela podera ser chamda outra vez
        Tela.mnuMetas.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameDeactivated

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    }//GEN-LAST:event_formInternalFrameActivated

    private void btReiniciarEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReiniciarEmprestimosActionPerformed
        //Botão para reiniciar o progresso e a meta dos Empréstimos
        
        String sql = " UPDATE metas SET Progresso = 0 , Meta = 0 WHERE Categoria = 'Emprestimos' ; ";
        try{
            DAO dao = new DAO();
            Connection conn = dao.conectar();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.execute();
            ps.close();

        }catch (SQLException se) {
            se.printStackTrace();
        }
        attMetasNaTelaEmprestimos();
    }//GEN-LAST:event_btReiniciarEmprestimosActionPerformed

 
    private void btSalvarMetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarMetasActionPerformed
        double mtSalario;
        double mtEmprestimos;
        double mtInvestimentos;
        double mtOutros;
        //Aqui vamos ver se tem alguns campos vazios , se tiver vamos setar 0 como padrão        
        if(tbMetaSalario.getText().isEmpty()){tbMetaSalario.setText("0");};
        if(tbMetaEmprestimos.getText().isEmpty()){tbMetaEmprestimos.setText("0");};
        if(tbMetaInvestimentos.getText().isEmpty()){tbMetaInvestimentos.setText("0");};
        if(tbMetaOutrasReceitas.getText().isEmpty()){tbMetaOutrasReceitas.setText("0");};
        
        mtSalario = Double.parseDouble(tbMetaSalario.getText());
        mtEmprestimos = Double.parseDouble(tbMetaEmprestimos.getText());
        mtInvestimentos = Double.parseDouble(tbMetaInvestimentos.getText());
        mtOutros = Double.parseDouble(tbMetaOutrasReceitas.getText());
       
        //Agora chamamos os métodos que irão fazer a inserção das metas
        salvarMetaSalario(mtSalario);
        salvarMetaEmprestimo(mtEmprestimos);
        salvarMetaInvestimentos(mtInvestimentos);
        salvarMetaOutros(mtOutros);
        //e chamamos os metodos que atualizar a tela
        attMetasNaTelaSalario();
        attMetasNaTelaEmprestimos();
        attMetasNaTelaInvestimentos();
        attMetasNaTelaOutros();
        //Vamos mandar a mensagem de metas salvas
        JOptionPane.showMessageDialog(null,"Metas Salvas com sucesso");
        
    }//GEN-LAST:event_btSalvarMetasActionPerformed

    private void tbProgressoSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbProgressoSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbProgressoSalarioActionPerformed

    private void btReiniciarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReiniciarSalarioActionPerformed
        //Botão para reiniciar o progresso e a meta de Salário
        String sql = " UPDATE metas SET Progresso = 0 , Meta = 0 WHERE Categoria = 'Salario' ; ";
        try{
            DAO dao = new DAO();
            Connection conn = dao.conectar();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.execute();
            ps.close();

        }catch (SQLException se) {
            se.printStackTrace();
        }
        attMetasNaTelaSalario();
    }//GEN-LAST:event_btReiniciarSalarioActionPerformed

    private void tbProgressoEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbProgressoEmprestimosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbProgressoEmprestimosActionPerformed

    private void tbProgressoInvestimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbProgressoInvestimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbProgressoInvestimentosActionPerformed

    private void btReiniciarInvestimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReiniciarInvestimentosActionPerformed
        //Botão para reiniciar o progresso e a meta dos Investimentos
        String sql = " UPDATE metas SET Progresso = 0 , Meta = 0 WHERE Categoria = 'Investimentos' ; ";
        try{
            DAO dao = new DAO();
            Connection conn = dao.conectar();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.execute();
            ps.close();

        }catch (SQLException se) {
            se.printStackTrace();
        }
        attMetasNaTelaInvestimentos();
    }//GEN-LAST:event_btReiniciarInvestimentosActionPerformed

    private void tbProgressoOutrasReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbProgressoOutrasReceitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbProgressoOutrasReceitasActionPerformed

    private void btReiniciarOutrasReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReiniciarOutrasReceitasActionPerformed
        //Botão para reiniciar o progresso e a meta das Outras Receitas
        String sql = " UPDATE metas SET Progresso = 0, Meta = 0 WHERE Categoria = 'Outras receitas' ; ";
        try{
            DAO dao = new DAO();
            Connection conn = dao.conectar();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.execute();
            ps.close();

        }catch (SQLException se) {
            se.printStackTrace();
        }
        attMetasNaTelaOutros();
    }//GEN-LAST:event_btReiniciarOutrasReceitasActionPerformed

    private void tbMetaSalarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMetaSalarioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMetaSalarioKeyReleased

    private void tbMetaEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMetaEmprestimosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMetaEmprestimosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgressoEmprestimos;
    private javax.swing.JProgressBar barraProgressoInvestimentos;
    private javax.swing.JProgressBar barraProgressoOutrasReceitas;
    private javax.swing.JProgressBar barraProgressoSalario;
    private javax.swing.JButton btReiniciarEmprestimos;
    private javax.swing.JButton btReiniciarInvestimentos;
    private javax.swing.JButton btReiniciarOutrasReceitas;
    private javax.swing.JButton btReiniciarSalario;
    private javax.swing.JButton btSalvarMetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tbMetaEmprestimos;
    private javax.swing.JTextField tbMetaInvestimentos;
    private javax.swing.JTextField tbMetaOutrasReceitas;
    private javax.swing.JTextField tbMetaSalario;
    private javax.swing.JTextField tbProgressoEmprestimos;
    private javax.swing.JTextField tbProgressoInvestimentos;
    private javax.swing.JTextField tbProgressoOutrasReceitas;
    private javax.swing.JTextField tbProgressoSalario;
    // End of variables declaration//GEN-END:variables


    public  void attMetasNaTelaSalario(){
        String sql = "SELECT *  FROM `metas` WHERE Categoria = 'Salario'  ; " ;
        try{
            DAO dao = new DAO();
            Connection conn = dao.conectar();
            PreparedStatement ps = conn.prepareStatement(sql);
            Statement st = conn.createStatement();;
            ResultSet rs = st.executeQuery(sql);     
            double resul = 0;
            double res = 0;
            while(rs.next()){
                tbProgressoSalario.setText(rs.getDouble("Progresso") + "");
                tbMetaSalario.setText(rs.getDouble("Meta") + "");
                barraProgressoSalario.setMaximum((int) rs.getDouble("Meta"));
                barraProgressoSalario.setValue((int) rs.getDouble("Progresso"));               
            }
        }catch(SQLException sqle){
            sqle.printStackTrace();
        }  
    }
    
    public  void attMetasNaTelaEmprestimos(){
        String sql = "SELECT *  FROM `metas` WHERE Categoria = 'Emprestimos'  ; " ;
        try{
            DAO dao = new DAO();
            Connection conn = dao.conectar();
            PreparedStatement ps = conn.prepareStatement(sql);
            Statement st = conn.createStatement();;
            ResultSet rs = st.executeQuery(sql);     
            double resul = 0;
            double res = 0;
            while(rs.next()){
                tbProgressoEmprestimos.setText(rs.getDouble("Progresso") + "");
                tbMetaEmprestimos.setText(rs.getDouble("Meta") + "");
                barraProgressoEmprestimos.setMaximum((int) rs.getDouble("Meta"));
                barraProgressoEmprestimos.setValue((int) rs.getDouble("Progresso"));               
            }
        }catch(SQLException sqle){
            sqle.printStackTrace();
        }  
    }
    
    public  void attMetasNaTelaInvestimentos(){
        String sql = "SELECT *  FROM `metas` WHERE Categoria = 'Investimentos'  ; " ;
        try{
            DAO dao = new DAO();
            Connection conn = dao.conectar();
            PreparedStatement ps = conn.prepareStatement(sql);
            Statement st = conn.createStatement();;
            ResultSet rs = st.executeQuery(sql);     
            double resul = 0;
            double res = 0;
            while(rs.next()){
                tbProgressoInvestimentos.setText(rs.getDouble("Progresso") + "");
                tbMetaInvestimentos.setText(rs.getDouble("Meta") + "");
                barraProgressoInvestimentos.setMaximum((int) rs.getDouble("Meta"));
                barraProgressoInvestimentos.setValue((int) rs.getDouble("Progresso"));               
            }
        }catch(SQLException sqle){
            sqle.printStackTrace();
        }  
    }
    
    public  void attMetasNaTelaOutros(){
        String sql = "SELECT *  FROM `metas` WHERE Categoria = 'Outras receitas'  ; " ;
        try{
            DAO dao = new DAO();
            Connection conn = dao.conectar();
            PreparedStatement ps = conn.prepareStatement(sql);
            Statement st = conn.createStatement();;
            ResultSet rs = st.executeQuery(sql);     
            double resul = 0;
            double res = 0;
            while(rs.next()){
                tbProgressoOutrasReceitas.setText(rs.getDouble("Progresso") + "");
                tbMetaOutrasReceitas.setText(rs.getDouble("Meta") + "");
                barraProgressoOutrasReceitas.setMaximum((int) rs.getDouble("Meta"));
                barraProgressoOutrasReceitas.setValue((int) rs.getDouble("Progresso"));               
            }
        }catch(SQLException sqle){
            sqle.printStackTrace();
        }  
    }
    
 
    
    public void salvarMetaSalario(Double meta){
        String sql = " UPDATE metas SET Meta = ? WHERE Categoria = 'Salario' ; ";
        try{
            DAO dao = new DAO();
            Connection conn = dao.conectar();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setDouble(1, meta);
            ps.execute();
            ps.close();

        }catch (SQLException se) {
            se.printStackTrace();
        }
    }
    
    public void salvarMetaInvestimentos(Double meta){
        String sql = " UPDATE metas SET Meta = ? WHERE Categoria = 'Investimentos' ; ";
        try{
            DAO dao = new DAO();
            Connection conn = dao.conectar();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setDouble(1, meta);
            ps.execute();
            ps.close();

        }catch (SQLException se) {
            se.printStackTrace();
        }
    }
    public void salvarMetaEmprestimo(Double meta){

        String sql = " UPDATE metas SET Meta = ? WHERE Categoria = 'Emprestimos' ; ";
        try{
            DAO dao = new DAO();
            Connection conn = dao.conectar();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setDouble(1, meta);
            ps.execute();
            ps.close();

        }catch (SQLException se) {
            se.printStackTrace();
        }
    }
    
    public void salvarMetaOutros(Double meta){
        String sql = " UPDATE metas SET Meta = ? WHERE Categoria = 'Outras receitas' ; ";  
        try{
            DAO dao = new DAO();
            Connection conn = dao.conectar();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setDouble(1, meta);
            ps.execute();
            ps.close();

        }catch (SQLException se) {
            se.printStackTrace();
        }
    }
    
    
    
    
    
    
    
    
    
}
